/* ==========================================
   KANJI STROKE DATA — on-demand fetch
   Unlike kana strokes (data/kana-strokes-data.js,
   inlined via <script> since there are only 208 of
   them), kanji strokes are one small JSON file per
   character under data/kanji/strokes/ (generated by
   scripts/generate-kanji-strokes.js) — fetched only
   for the one character currently being viewed, so
   this scales to thousands of kanji without bloating
   every page load. This means it needs the server
   running, same as login/dashboard/favorites already
   do — plain file:// won't serve it.
========================================== */

window.EasyNihongoKanjiStrokes = {
    async fetchStrokes(char) {
        try {
            const res = await fetch(`/data/kanji/strokes/${char.codePointAt(0)}.json`);
            if (!res.ok) return null;
            return await res.json();
        } catch {
            return null;
        }
    }
};
